name: build manifest
on: [push]
jobs:
  build_file:
    name: build manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Run build manifest script
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os, json
            configs = []
            for filename in os.scandir('configs'):
              with open(filename, mode='r', encoding='utf-8') as file:
                configs.append(json.load(file))
            with open("manifest.json", mode='w', encoding='utf-8') as f:
              f.truncate(0)
              json.dump(configs, f)
      - name: push new manifest file
        uses: EndBug/add-and-commit@v9
        with:
          add: 'manifest.json'
          committer_name: github actions
          committer_email: actions@github.com
          default_author: github_actions
          message: 'Create manifest file from configs by github action'
          push: true
