name: build unified manifest file
on: [push]
jobs:
  build_file:
    name: build unified manifest file
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run script
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os, json
            def flatten_data(y):
              out = {}
              def flatten(x, name=''):
                if type(x) is dict:
                  for a in x:
                    flatten(x[a], name + a + '_')
                elif type(x) is list:
                  i = 0
                  for a in x:
                    flatten(a, name + str(i) + '_')
                    i += 1
                else:
                  out[name[:-1]] = x
              flatten(y)
              return out
            with open("manifest.json", "r+") as t:
              t.truncate(0)
              t.write('[')
              first = True
              for filename in os.scandir('configs'):
                print(filename)
                with open(filename, "r") as f:
                  content = f.read()
                  flattenContent = flatten_data(content)
                  if first:
                    first = False
                  else:
                    t.write(',')
                  t.write(flattenContent)
              t.write(']')
            barak = open("manifest.json", "r+")
            contentb = barak.read()
            print(contentb)
      - name: push file to main
        uses: EndBug/add-and-commit@v9
        with:
          add: 'manifest.json'
          committer_name: Committer Name
          committer_email: mail@example.com
          default_author: github_actor
          message: 'Update manifest unified file'
          push: true
