
name: build and verify manifest
on: [push]
jobs:
  build_file:
    name: build and verify manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: python -m pip install requests
      - name: Build and verify manifest
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os, requests, json, sys
            configs = []
            for filename in os.scandir('configs'):
              with open(filename, mode='r', encoding='utf-8') as file:
                configs.append(json.load(file))
            with open("manifest.json", mode='w', encoding='utf-8') as f:
              f.truncate(0)
              json.dump(configs, f)
            
            # Validate new manifest
            url = 'https://app.logz.io/telemetry-agent/public/manifest/validate'
            with open("manifest.json", mode='r', encoding='utf-8') as f:
              manifest = json.load(f)
              response = requests.post(url, json = manifest)
            isValid = response.json()['valid']
            if isValid != True:
              message = (response.json()['message'])
              sys.exit(message)
            else:
              print('Validation pass')
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            configs:
              - 'configs/**'
      - name: push new manifest file
        if: steps.filter.outputs.configs == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'manifest.json'
          committer_name: github actions
          committer_email: actions@github.com
          default_author: github_actions
          message: 'Create manifest file from configs by github action'
          push: true
      - name: update testing pre release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          prerelease: true
          name: testing
          files: manifest.json
          allow_override: true
          gzip: false


