name: build unified manifest file
on: [push]
jobs:
  build_file:
    name: build unified manifest file
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
      with:
        script: |
          import os
          print("Directory contents:")
          for f in os.listdir():
              print(f)
          print(os.getcwd())
      - name: push file to main
        uses: EndBug/add-and-commit@v9
        with:
          add: 'manifest.json'
          committer_name: Committer Name
          committer_email: mail@example.com
          default_author: github_actor
          message: 'Update manifest unified file'
          push: true
