name: build unified manifest file
on: [push]
jobs:
  build_file:
    name: build unified manifest file
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run script
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os, json, shutil
            with open("manifest.json", "r+") as t:
              t.truncate(0)
              t.write('[')
              for filename in os.scandir('configs'):
                print(filename)
                with open(filename, "r") as f:
                  content = f.read()
                  t.write(content)
                  t.write(',')
              t.seek(-1, os.SEEK_END)
              t.truncate()
              t.write(']')
            barak = open("manifest.json", "r+")
            contentb = barak.read()
            print(contentb)
      - name: push file to main
        uses: EndBug/add-and-commit@v9
        with:
          add: 'manifest.json'
          committer_name: Committer Name
          committer_email: mail@example.com
          default_author: github_actor
          message: 'Update manifest unified file'
          push: true
