name: build manifest
on: [push]
jobs:
  build_file:
    name: build manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
      - name: Run script
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os, json
            configs = []
            for filename in os.scandir('configs'):
              with open(filename, mode='r', encoding='utf-8') as file:
                configs.append(json.load(file))
            with open("manifest.json", mode='w', encoding='utf-8') as f:
              f.truncate(0)
              json.dump(configs, f)
      - name: push file to main
        uses: EndBug/add-and-commit@v9
        with:
          add: 'manifest.json'
          committer_name: Committer Name
          committer_email: mail@example.com
          default_author: github_actor
          message: 'Update manifest'
          push: true
