name: build unified manifest file
on: [push]
jobs:
  build_file:
    name: build unified manifest file
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run script
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os, json
            @get_items.register(dict)
              def _(obj):
                return obj.items() # json object. Edit: iteritems() was removed in Python 3
            def flatten(json_data):
              for key, value in get_items(json_data):
                if hasattr(value, 'strip'):
                  json_data[key] = value.strip()
                else:
                  strip_whitespace(value)
            with open("manifest.json", "r+") as t:
              t.truncate(0)
              t.write('[')
              first = True
              for filename in os.scandir('configs'):
                print(filename)
                with open(filename, "r") as f:
                  if first:
                    first = False
                  else:
                    t.write(',')
                  content = f.read()
                  t.write(json.dumps(content,indent=None))
              t.write(']')
      - name: push file to main
        uses: EndBug/add-and-commit@v9
        with:
          add: 'manifest.json'
          committer_name: Committer Name
          committer_email: mail@example.com
          default_author: github_actor
          message: 'Update manifest unified file'
          push: true
