name: build manifest
on: [push]
jobs:
  build_file:
    name: build manifest
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run script
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            with open("manifest.json", "r+") as t:
              t.truncate(0)
              t.write('[')
              first = True
              for filename in os.scandir('configs'):
                if first:
                  first = False
                else:
                  t.write(',')
                with open(filename, "r") as f:
                  content = f.read()
                t.write(content)
              t.write(']')
      - name: ValidateJSON
        uses: TobiasOlofsson88/github-action-validate-json-request-result@v1.0.5
        with:
          request-method: "POST"
          request-url: "https://app.logz.io/telemetry-agent/public/manifest/validate"
          request-headers: '{ "Content-Type": "application/json" }'
          request-body: '{ "Attribute": "Value" }'
          should-fail: false
      - name: push file to main
        uses: EndBug/add-and-commit@v9
        with:
          add: 'manifest.json'
          committer_name: Committer Name
          committer_email: mail@example.com
          default_author: github_actor
          message: 'Update manifest'
          push: true
