name: build manifest
on: [push]
jobs:
  build_file:
    name: build manifest
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run script
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os, requests, json
  
            url = 'https://app.logz.io/telemetry-agent/public/manifest/validate'

            with open("manifest.json", mode='r', encoding='utf-8') as f:
              manifest = json.load(f)
              
              response = requests.post(url, json = manifest, verify=False)
            
            message = response.json()['message']
            if message != 'valid':
              core.setFailed(message)