name: verify manifest
on: [push]
jobs:
  build_file:
    name: verify manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: python -m pip install requests
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os, requests, json, core
  
            url = 'https://app.logz.io/telemetry-agent/public/manifest/validate'

            with open("manifest.json", mode='r', encoding='utf-8') as f:
              manifest = json.load(f)
              
              response = requests.post(url, json = manifest, verify=False)
            
            message = response.json()['message']
            if message != 'valid':
              error(message)